[package]
name = "tetsy-impl-rlp"
version = "0.3.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/tetcoin/tetsy-common"
description = "Tetsy RLP serialization support for uint and fixed hash."
edition = "2018"

[dependencies]
tetsy-rlp = { version = "0.5.1", path = "../../../tetsy-rlp", default-features = false }

[features]
default = ["std"]
std = ["tetsy-rlp/std"]
