environment:
  matrix:
    - FEATURES: ""

platform:
  - x86_64-pc-windows-msvc

# avoid running tests twice
branches:
  only:
    - master

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %PLATFORM%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
  - cargo check --tests
  - cargo build --all

test_script:
  - cargo test --all --exclude uint --exclude tetsy-fixed-hash
  - cd tetsy-fixed-hash/ && cargo test --all-features && cd ..
  - cd uint/ && cargo test --features=std,quickcheck --release && cd ..
  - cd tetsy-plain-hasher/ && cargo test --no-default-features && cd ..
  - cd tetsy-util-mem/ && cargo test --no-default-features && cd ..
  - cd tetsy-util-mem/ && cargo test --features=estimate-heapsize && cd ..
  - cd tetsy-util-mem/ && cargo test && cd ..
