[package]
name = "tetsy-bytes"
version = "0.1.4"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/tetcoin/tetsy-common"
description = "Byte utilities for Tetsy"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]

[features]
default = ["std"]
std = []
