[package]
name = "tetsy-rlp"
version = "0.5.1"
description = "Tetsy Recursive-length prefix encoding, decoding, and compression"
repository = "https://github.com/tetcoin/tetsy-common"
license = "MIT OR Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bytes = { version = "1", default-features = false }
rustc-hex = { version = "2.0.1", default-features = false }

[dev-dependencies]
criterion = "0.3.0"
hex-literal = "0.3.1"
tetsy-primitive-types = { path = "../tetsy-primitive-types", features = ["tetsy-impl-rlp"] }

[features]
default = ["std"]
std = ["bytes/std", "rustc-hex/std"]

[[bench]]
name = "rlp"
path = "benches/rlp.rs"
harness = false
