[package]
name = "tetsy-util-mem-derive"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT OR Apache-2.0"
description = "Tetsy Common Crate for Memory Reporting"
repository = "https://github.com/paritytech/pariry-common/tetsy-util-mem/derive"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full"] }
synstructure = "0.12"
