[package]
name = "tetsy-impl-serde"
version = "0.3.2"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/tetcoin/tetsy-common"
description = "Tetsy Serde serialization support for uint and fixed hash."

[features]
default = ["std"]
std = ["serde/std"]

[dependencies]
serde = { version = "1.0.101", default-features = false, features = ["alloc"] }

[dev-dependencies]
criterion = "0.3.0"
serde_derive = "1.0.101"
serde_json = "1.0.41"
uint-crate = { version = "0.9.1", path = "../../../uint-crate" }

[[bench]]
name = "impl_serde"
harness = false
