[package]
name = "tetsy-path"
version = "0.1.4"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/tetcoin/tetsy-common"
description = "Tetsy Path utilities"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
home = "0.5.1"
