name: Rust - Debug Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        run: cargo check --tests

      - name: Build
        run: cargo build --all

      - name: Run tests
        run: |
          cargo test --all --exclude uint --exclude tetsy-fixed-hash
          cd tetsy-fixed-hash/ && cargo test --all-features && cd ..
          cd uint-crate/ && cargo test --features=std,quickcheck --release && cd ..
          cd tetsy-plain-hasher/ && cargo test --no-default-features && cd ..
          cd tetsy-util-mem/ && cargo test --no-default-features && cd ..
          cd tetsy-util-mem/ && cargo test --features=estimate-heapsize && cd ..
          cd tetsy-util-mem/ && cargo test && cd ..
